version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    command: "start-dev"

  config-service:
    build: ./services/config-service
    container_name: config-service
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api-gateway-service:
    build: ./services/api-gateway-service
    container_name: api-gateway-service
    ports:
      - "8080:80" # Entry point for the application
    depends_on:
      config-service:
        condition: service_healthy

  identity-service:
    build: ./services/identity-service
    container_name: identity-service
    depends_on:
      config-service:
        condition: service_healthy

  catalog-service:
    build: ./services/catalog-service
    container_name: catalog-service
    depends_on:
      config-service:
        condition: service_healthy

  order-service:
    build: ./services/order-service
    container_name: order-service
    depends_on:
      config-service:
        condition: service_healthy

  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    depends_on:
      config-service:
        condition: service_healthy

  payment-service:
    build: ./services/payment-service
    container_name: payment-service
    depends_on:
      config-service:
        condition: service_healthy
